name: NetWorth
author: iAtomPlaza
version: 2.0.1
api: 1.0.9
main: NetWorth.Main
depend:
  - NukkitDB
  - PlayerAPI
permissions:
  networth.admin:
    description: allows ussage of admin override commands
    default: op